# Generated by Django 6.1.1 on 2026-10-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=100)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('heart_rate', models.PositiveIntegerField()),
                ('spo2', models.PositiveIntegerField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
